import type { AnswerKind, LocalizedLatex, LocalizedText } from '../types'
import type { Rng } from './rng'

export type Generated = {
  /** Instruction shown above the formula box, plain prose. */
  instruction: LocalizedText
  /** The question itself, as LaTeX, rendered large by KaTeX. */
  prompt: LocalizedLatex
  /** Canonical answer in infix notation. Known before the question exists. */
  answer: string
  answerKind: AnswerKind
  /** Worked solution, revealed after a wrong answer. Precomputed, never generated by an LLM. */
  steps: LocalizedLatex[]
  /** Progressive nudges, revealed on request before answering. */
  hints: LocalizedText[]
}

export type Level = {
  /** e.g. "linear-equations.L6" */
  id: string
  /** 1..9 */
  number: number
  concept: LocalizedText
  generate(rng: Rng, scale: number): Generated
}

export type Topic = {
  id: string
  name: LocalizedText
  /** KSSM chapter number for Form 1. */
  chapter: number
  levels: Level[]
}

export const CONCEPT_LEVELS = 9

/**
 * Levels 1-9 run their own generator at scale 0. Above 9 there is no new
 * generator: level n reuses level 9 with scale n-9, which widens the parameter
 * space without introducing a new concept.
 */
export function resolveLevel(topic: Topic, level: number): { level: Level; scale: number } {
  const index = Math.min(Math.max(level, 1), CONCEPT_LEVELS)
  return {
    level: topic.levels[index - 1],
    scale: Math.max(0, level - CONCEPT_LEVELS),
  }
}
